# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: DefaultOpenShift

steps:
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ARO_local_dev_cluster_redhat83'
    cmd: 'oc projects'
    uselocalOc: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ARO_local_dev_cluster_redhat83'
    cmd: 'oc project myapp'
    uselocalOc: true
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ARO_local_dev_cluster_redhat83'
    cmd: 'oc start-build nodejs-ex  --follow'
    uselocalOc: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ARO_local_dev_cluster_redhat83'
    cmd: 'oc status'
    uselocalOc: true
