# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  name: DefaultLinuxOnPremPool

steps:
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ARO_local_dev_cluster_redhat83'
    cmd: 'oc projects'
    uselocalOc: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ARO_local_dev_cluster_redhat83'
    cmd: 'oc project myapp'
    uselocalOc: true
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ARO_local_dev_cluster_redhat83'
    cmd: 'oc start-build nodejs-ex  --follow'
    uselocalOc: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ARO_local_dev_cluster_redhat83'
    cmd: 'oc status'
    uselocalOc: true
